#!/bin/bash

source bin/config

# handle help
if [ $# -eq 0 ]; then
  echo -e "Usage: ./submit TASK_ON_SITE"
  echo
  echo -e "Submits task according to cion rules."
  echo
  echo -e "TASK_ON_SITE={"
  echo -e "${BLANK}hw1:${RESET}  1,  2, 10, 17, 31,  33,  38,  44, 53, 62;"
  echo -e "${BLANK}hw2:${RESET} 11, 12, 15, 20, 22,  29,  30,  68, 74, 86;"
  echo -e "${BLANK}hw3:${RESET}  7,  9, 14, 16, 23,  32,  48,  84;"
  echo -e "${BLANK}hw4:${RESET} 37, 41, 47, 70, 73,  87, 102, 112;"
  echo -e "${BLANK}hw5:${RESET} 65, 82, 90, 96, 98, 100, 105, 109;"
  echo -e "}"
  exit 0
fi

while [ $# -gt 0 ]; do
  TASK_ON_SITE=$1
  shift

  source bin/map $TASK_ON_SITE

  bin/checkout $HW $ORD_NUM

  echo "Enter file contetns for task $TASK_ON_SITE:"
  bin/create $HW $TASK_ON_SITE

  while true; do
    read -p "Check file contents! Are you sure you want to submit? (Y/n)" yn
    case $yn in
      Y) break;;
      n) exit;;
    esac
  done

  echo "Enter commit comment(${ORD_NUM}-${TASK_ON_SITE}):"
  bin/commit $HW $ORD_NUM
done 

echo "You can visit, to create all the merge requests"
echo "  https://gitlab2.atp-fivt.org/db2021/borodinsa-${HW}/-/branches/all"
